services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn application.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_HOSTNAME=postgres # this value is same as the ref:tag_postgres, docker internally resolves the hostname to point it to DB
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=300

  postgres:
    # tag_postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fastapi

    volumes:
      - postgres-db:/var/lib/postgresql/data # mount a volume to persist data even after container destruction, the value is the default dir where postgres stores it's data

volumes:
  postgres-db: # named bolume: for reusability of other container applications
